### ISSUE TITLE
Vulnerability  CVE-2024-4367

### ISSUE THREAD

**Issue by AaronSterlingGENEICD** [electrovir/pdf-text-reader#10]
Please update to pdfjs-dist 4.2.67 or later, because of this vulnerability: https://github.com/advisories/GHSA-wgrm-67xf-hhpq

We tried to do it with an npm override, but we got this error message:

```
node_modules/pdf-text-reader/dist/read-pdf.d.ts:1:15 - error TS2305: Module '"pdfjs-dist/types/src/display/api"' has no exported member 'BinaryData'.

1 import type { BinaryData, DocumentInitParameters, PDFPageProxy, TextItem } from 'pdfjs-dist/types/src/display/api';
                ~~~~~~~~~~

node_modules/pdf-text-reader/dist/read-pdf.d.ts:3:15 - error TS2305: Module '"pdfjs-dist/types/src/display/api"' has no exported member 'BinaryData'.

3 export type { BinaryData, DocumentInitParameters } from 'pdfjs-dist/types/src/display/api';
```
Thank you!

**Comment by electrovir** [comment]
Done and published as version 5.0.0: https://www.npmjs.com/package/pdf-text-reader/v/5.0.0.

Note that the upgrade placed several _new_ restrictions on this package. Specifically:

- it now only supports Node.js 22 and above
- it is now exported as ESM rather than CommonJS

These requirements are from `pdfjs-dist` itself.

See https://github.com/electrovir/pdf-text-reader/commit/ff6193963c868158b750136b007743e67cf36ba1 for details.

**Comment by AaronSterlingGENEICD** [comment]
Thanks very much for pushing a change so quickly. I found errors when I compiled, all related to the change in syntax of an ESM import.

- dist/index should read `export * from './read-pdf.js';` (add a .js to the end of the import location)
- import and export in read-pdf.ts needs to be from api.ts (or maybe js), not just from api

Documentation: https://nodejs.org/api/esm.html#mandatory-file-extensions

**Comment by electrovir** [comment]
Thanks @AaronSterlingGENEICD, lets track that in #11
